### PR TITLE
Add syntax check

### PR DESCRIPTION
**Pull request by szepeviktor**
and fix CI steps

### CODE REVIEW

**Comment by szepeviktor** [comment]
Tests passed 🍏 

Only the coding standard check left.
Do you follow PSR-12?

**Comment by sprain** [comment]
Thank you for your contribution!

Any specific reason why you added the syntax check? I think PhpStan should already detect such issues.

> Do you follow PSR-12?

We follow Symfony coding standards.
https://symfony.com/doc/current/contributing/code/standards.html

**Comment by szepeviktor** [comment]
> Any specific reason why you added the syntax check?

My basic trio of tests are

1. syntax check
1. coding standard
1. static analysis

> I think PhpStan should already detect 

Have you tried to plant a syntax error in the source code?

**Comment by szepeviktor** [comment]
This can be seen as a syntax check

kép

although my one-liner is a light and robust way of checking for syntax errors.

**Comment by sprain** [comment]
Thanks for that one, too!

**Pull request merged**
