### PR TITLE
Secure Card Data Alias Insert/Inser Assert  & Transaction Initialize/Authorize Requests

### PR DESCRIPTION
**Pull request by thomasmeike**
a new name space Ticketpark\SaferpayJson\SecureAliasStore has been added covering e.g. credit-card registration and the corresponding request-assertion 

the new class SecureAliasStore\AliasInsertRequest can be used to register means of payment: CARD, BANK_ACCOUNT, POSTFINANCE

the new class SecureAliasStore\AliasInsertAssertRequest is used to make an authoritative confirmation request about the successful registration

the new class Transaction\InitializeRequest is used to initialize payment requests for an alias

the new class Transaction\AuthorizationRequest is used to finally process an open payment initialization

Mit freundlichen Grüßen / best regards

DI(Fh) Thomas Meike
nic.at IT
__________________________________________________

nic.at GmbH
Jakob-Haringer-Str. 8/V
5020 Salzburg, Austria

Tel: +43 662 46 69-66
Fax: +43 662 46 69-19

E-Mail: thomas.meike@nic.at
Web: http://www.nic.at

UID-Nr.: ATU 45305101
LG Salzburg / FN 172568b
Sitz / location: Salzburg
DVR-Nr.: 0968935

### CODE REVIEW

**Comment by sprain** [comment]
Thanks, will have a look.
Would you mind taking care of the failing tests in the meantime?

**Comment by thomasmeike** [comment]
done
cheers thomas

**Comment by sprain** [comment]
I think, this needs some cleanups and I started working on them here:
https://github.com/Ticketpark/SaferpayJsonApi/pull/3

**Comment by thomasmeike** [comment]
> Improve class structure. For example, Ticketpark\SaferpayJson\SecureAliasStore\AssertInsertResponse extending Ticketpark\SaferpayJson\PaymentPage\AssertResponse is not very nice as with these namespaces it's not a parent-
> child-relationship.

Ok, how about including Traits instead with some common getter , setter  functions?



Von: Manuel Reinhard [mailto:notifications@github.com] 
Gesendet: Montag, 25. Juli 2016 19:56
An: Ticketpark/SaferpayJsonApi <SaferpayJsonApi@noreply.github.com>
Cc: Thomas Meike <thomas.meike@nic.at>; Author <author@noreply.github.com>
Betreff: Re: [Ticketpark/SaferpayJsonApi] Secure Card Data Alias Insert/Inser Assert & Transaction Initialize/Authorize Requests (#2)

I think, this needs some cleanups and I started working on them here:
https://github.com/Ticketpark/SaferpayJsonApi/pull/3

**Comment by sprain** [comment]
> Ok, how about including Traits instead with some common getter , setter  functions?

This might be an idea. However, I would do this in an additional second step to avoid blowing up this task.

**Comment by sprain** [comment]
Thanks again for your pull request.

I did some cleanups and added examples. Do you want to give it a try before we merge?
https://github.com/Ticketpark/SaferpayJsonApi/pull/3

Please note that I temporarily removed the additional Transaction requests to keep topics separated. There is a new issue for that: https://github.com/Ticketpark/SaferpayJsonApi/issues/4

Also, I changed some class names to be consistent with the existing classes as well as with the actual api namings. You might have to update your project code accordingly.

**Comment by thomasmeike** [comment]
Thanks to you for the great and intuitively to use library ;)

 

I`ve applied your latest changes within our source, leaving the 

additional transaction classes so far unchanged, as they are currently in use

until issue #4 has been brought to an end.

 

Cheers 

Thomas

 

Von: Manuel Reinhard [mailto:notifications@github.com] 
Gesendet: Dienstag, 26. Juli 2016 17:49
An: Ticketpark/SaferpayJsonApi <SaferpayJsonApi@noreply.github.com>
Cc: Thomas Meike <thomas.meike@nic.at>; Author <author@noreply.github.com>
Betreff: Re: [Ticketpark/SaferpayJsonApi] Secure Card Data Alias Insert/Inser Assert & Transaction Initialize/Authorize Requests (#2)

 

Thanks again for your pull request.

I did some cleanups and added examples. Do you want to give it a try before we merge?
#3 <https://github.com/Ticketpark/SaferpayJsonApi/pull/3> 

Please note that I temporarily removed the additional Transaction requests to keep topics separated. There is a new issue for that: #4 <https://github.com/Ticketpark/SaferpayJsonApi/issues/4> 

Also, I changed some class names to be consistent with the existing classes as well as with the actual api namings. You might have to update your project code accordingly.

**Comment by sprain** [comment]
Ok, great!

I will close this PR and instead merge #3 into master. You might want to subscribe to #4 to be updated when the Transactions have been implemented.

**Pull request closed without merging**
