### PR TITLE
Check CS

### PR DESCRIPTION
**Pull request by szepeviktor**
as per https://github.com/Ticketpark/SaferpayJsonApi/pull/21#issuecomment-621151150

### CODE REVIEW

**Comment by szepeviktor** [comment]
Use
... php-cs-fixer-v2

**Comment by szepeviktor** [comment]
All green 🍏

**Comment by sprain** [comment]
Thank you for the contribution!
I moved `php-cs-fixer` to composer.json and merged your changes [in this commit](https://github.com/Ticketpark/SaferpayJsonApi/commit/14d4f686cabd7bffa9cff4327f8d7a7d16eb5f83).

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by szepeviktor** [comment]
@sprain Actually you could run these 3 tests in other PHP projects also.
These are the basis of robust code.

**Pull request closed without merging**
