### PR TITLE
v3

### PR DESCRIPTION
**Pull request by sprain**
This is a major refactoring for version 3:

* Update to most current Saferpay API version 1.17
* Separate containers by response and request
* Use constructors to enforce mandatory data
* Handle Saferpay error response as exception
* Introduce stricter handling of inheritance within classes

### CODE REVIEW

**Comment by szepeviktor** [comment]
You must remember we talked about automatic getter/setters.

What do you think about creating a JSON schema and generating our code/or automate things based on that?
Although we will receive no schema from SIX: https://github.com/saferpay/jsonapi/pull/20

**Comment by sprain** [comment]
> What do you think about creating a JSON schema for Saferpay API and generating our code/or automate things based on that?

Yes, I thought about this, too. It would definitely make development simpler. It can still be added later without breaking a v3 release.

**Comment by szepeviktor** [comment]
@sprain How come that master does not contain these changes even though this PR was merged?
https://github.com/Ticketpark/SaferpayJsonApi/commits/master

**Comment by sprain** [comment]
I merged by accident and undid it again.
I first want to try with a release candidate based on the v3-branch in my applications. See https://github.com/Ticketpark/SaferpayJsonApi/releases

**Comment by szepeviktor** [comment]
I see!

Do unit tests excercise Saferpay sandbox?

**Pull request merged**
