### PR TITLE
saferpay api update 1.23 => 1.31

### LINKED ISSUE #60: Implement changes of Saferpay API 1.24
http://saferpay.github.io/jsonapi/#v1.24.0.0.20210914

### PR DESCRIPTION
**Pull request by giriroub**
Closes #60, #61, #62, #63, #64, #71, #72, #73

This PR contains all changes from 1.23 to 1.31, according to http://saferpay.github.io/jsonapi/#changelog

### CODE REVIEW

**Comment by sprain** [comment]
Thank you very much for this valuable contribution!

I added some more changes in #93 (mostly replaced serializer types with native property types) and merged this. If you want, you are welcome to take the current master branch on a test drive as a potential v5.0 of this library.

**Comment by giriroub** [comment]
> If you want, you are welcome to take the current master branch on a test drive as a potential v5.0 of this library.
We are directly testing https://github.com/i-web/SaferpayJsonApi/tree/Saferpay-Api-Update-BC this week (we need 1.37 because of the new PaymentMethod POSTFINANCEPAY) and are planning on taking it to production by the end of the week.

**Comment by sprain** [comment]
@giriroub How did your release go?

**Comment by giriroub** [comment]
The release passed all our tests, but we haven't deployed it yet. Due to other circumstances this might take another couple weeks.

**Pull request merged**
