### PR TITLE
Added Transactions

### PR DESCRIPTION
**Pull request by sprain**
Work in progress for issued #4.

### CODE REVIEW

**Comment by jmverges** [comment]
Hi there, 
why this is not merged?  Was done more than 1 year ago and looks ok.

Cheers

**Comment by sprain** [comment]
> why this is not merged?

Missing time and actually still a work in progress. Sorry!

**Comment by jmverges** [comment]
@sprain this is a good library. Keep it alive!

**Comment by sprain** [comment]
This pr is outdated and will therefore be closed.

**Pull request closed without merging**
